### ISSUE TITLE
Add a way to change the DEBUG parameter in the C code from Python

### ISSUE THREAD

**Issue by astrofrog** [astropy/reproject#21]
This is low priority, but in the long term it would be nice to be able to enable debugging of the C routines from the Python code.

**Comment by jamienoss** [comment]
Just saw this while looking at others, I'm not 100% sure of what you are referring to, but if it's the macro def ``DEBUG``, what you ask for is not possible without rebuilding the C code. You could _always_ build the C with ``-g`` so that the symbol table is populated, there's no harm in doing this. The assertion handling on the other hand is the thing (normally) controlled by the ``DEBUG`` macro. This can be changed at build time with ``-DDEBUG`` and ``-UNDEBUG``. Again though, this is a preprocessor entity.

You could make this an rt conditional but I would advise against it, it would impact everything and debug statements are suppossed to be non-interferring, which is why they're ``#if``s.

I might, of course, have the wrong end of the stick.
