### ISSUE TITLE
find_optimal_celestial_wcs does not accept GWCS

### ISSUE THREAD

**Issue by pllim** [astropy/reproject#328]
https://github.com/astropy/reproject/blob/aa23eb13aec929cd3719b8d245362a77a33007c3/reproject/mosaicking/wcs_helpers.py#L92

It complains that GWCS has no attribute `naxis`.

**Comment by astrofrog** [comment]
I investigated this a bit and there are two main things to do/consider here:

* There are a number of places in this function where we assume the input WCS is a FITS WCS, so that will require a bit of thinking. I think we might want to keep the current code for FITS WCS and then write a general APE 14 fallback (I think we should keep the FITS-specific code for backward compatibility and also because there are some things we do smartly if it is a FITS WCS).

* We currently construct a FITS WCS as the output - I don't think we could easily change this to depend on the input type as it would be a lot of special casing, but I think it would be reasonable to always use FITS WCS as the output if there are no objections?

**Comment by pllim** [comment]
> I think it would be reasonable to always use FITS WCS as the output if there are no objections?

I dunno. GWCS exists to handle distortions that FITS WCS cannot, so if that is not an issue here, then maybe it is okay but I'll ping @nden and @WilliamJamieson to comment.

**Comment by astrofrog** [comment]
@pllim - indeed but this is a WCS that the data would get reprojected *to*, so it's not like the case of raw data when you need GWCS to represent the coordinate system without any resampling. The target WCS doesn't have to have any relation to the original pixel gridding/distortions.

**Comment by pllim** [comment]
So, if I want to reproject a distorted GWCS to another distorted GWCS, is the distortion ignored? Or is distortion ignored in all cases regardless anyway?

**Comment by astrofrog** [comment]
There are two separate things here:

- reproject can reproject images with/without distortions to WCSes with/without distortions. It will respect the input/output WCS and that means taking into account distortions.

- The function here is designed to find an 'ideal' output WCS given one or more input WCSes and doesn't include distortions in the returned WCS (because if you are going to reproject/mosaic, why would you want to keep distortions?)

If what you want is to apply a pure rotation to an existing WCS and preserve distortions etc then it's best to just edit the WCS, eg in GWCS you would add a rotation component. Does this make sense?

**Comment by pllim** [comment]
Maybe... but it really depends on what @orifox wanted to do with this function. I used this because of the code he provided for Imviz rotation work.
